services:
  object-tracking-env:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ONNX_VERSION=1.16.3
      # Explicitly set the platform for Mac M4
      platforms:
        - linux/arm64
    image: object-tracking-env:latest
    container_name: object-tracking-env
    volumes:
      - .:/app
      - ${PWD}/_dataset:/app/_dataset  # Use absolute path with PWD
      - /tmp/.X11-unix:/tmp/.X11-unix  # X11 socket for display
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
    # Interactive mode so you can execute commands inside
    stdin_open: true
    tty: true
    # Add a sleep command to keep the container running
    command: tail -f /dev/null