services:
  object-tracking-env:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ONNX_VERSION=1.16.3
      # Explicitly set the platform for Mac M4
      platforms:
        - linux/arm64
    image: object-tracking-env:latest
    container_name: object-tracking-env
    volumes:
      - .:/app
      - ${PWD}/_dataset:/app/_dataset
      - ${PWD}/config:/app/config
      - ${PWD}/output:/app/output
      # X11 socket for display
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY:-host.docker.internal:0}
    # Interactive mode
    stdin_open: true
    tty: true