# docker-compose.yml
services:
  object-tracking:
    build: .
    volumes:
      - ./output:/app/output
      - ./config:/app/config
      - ../_dataset:/app/_dataset  # Mount dataset directory
      - /tmp/.X11-unix:/tmp/.X11-unix  # Add X11 socket mounting
    environment:
      - DISPLAY=host.docker.internal:0  # This is for macOS
      - XDG_RUNTIME_DIR=/tmp/runtime-dir
      - QT_X11_NO_MITSHM=1
    extra_hosts:
      - "host.docker.internal:host-gateway"  # This is for macOS
    privileged: true